import type { LessonPlan } from "@/types";
import { downloadFile, sanitizeFilename } from "./utils";

export function generateLessonPlanMarkdown(plan: LessonPlan): string {
  return `# Lesson Plan: ${plan.topic}

**Grade Level:** ${plan.gradeLevel}  
**Subject:** ${plan.subject}  
**Date:** ${new Date().toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" })}

---

## I. Objectives

${plan.objectives.map((obj, i) => `${i + 1}. ${obj}`).join("\n")}

---

## II. Subject Matter

**Topic:** ${plan.topic}

**Materials:**
${plan.materials.map((mat) => `- ${mat}`).join("\n")}

---

## III. Procedure

### A. Introduction / Motivation
${plan.procedure.introduction}

### B. Development / Presentation
${plan.procedure.development}

### C. Practice / Application
${plan.procedure.practice}

### D. Assessment / Evaluation
${plan.procedure.assessment}

### E. Closure / Summary
${plan.procedure.closure}

---

## IV. Evaluation

${plan.evaluation}

${plan.assignment ? `---\n\n## V. Assignment\n\n${plan.assignment}` : ""}

----

*Generated by SmartClass - AI-Assisted Lesson Planning Tool*
`;
}

export function downloadLessonPlan(topic: string, markdown: string): void {
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const filename = `lesson_plan_${sanitizeFilename(topic)}.md`;
  downloadFile(blob, filename);
}
